### ISSUE TITLE
Try resizing the avatars

### ISSUE THREAD

**Issue by kira-abl** [FACN7/ma-reactproject#5]
When one person has a large image as his avatar, and the other person has a small image, you get two different sizes and cannot see the score easily.

**Comment by kira-abl** [comment]
![Screen Shot 2019-11-14 at 10 32 04 AM](https://user-images.githubusercontent.com/32569307/68839871-3d4f7780-06ca-11ea-8b8e-9b550b236f91.png)

**Comment by MohamadD** [comment]
done!
